### ISSUE TITLE
Delete empty lines

### ISSUE THREAD

**Issue by EvilOlaf** [bassamanator/armbian-orangepi-how-to#1]
Hey, 
just curious. You mentioned

> ⚠️❗ Delete all comments (lines starting with #) and all empty lines!

Why is this necessary? Did this cause trouble?

Cheers

**Comment by bassamanator** [comment]
Well I was having an issue with the new user not being created. Part of the `.not_logged_in_would` would work, but only part of it. The problem was that `PRESET_LOCALE=en_CA.UTF-8` was not working, it needs to be `PRESET_LOCALE=en_US.UTF-8` regardless, I learned this after 6 or so image flashes. Before I discovered that the true issue was `locale`, I tried to solve the problem by removing on the comments and empty lines. So that warning is a remnant of my problem solving.

It's possible that comments and empty lines are okay, I'll test this out in the next couple of days.

**Comment by bassamanator** [comment]
And thanks for your help on the Armbian forums! I've become quite a fan of Armbian, and I'm currently trying to figure out how to easily add the Armbian logo to my newly designed case for the OrangePi Zero 2W. 
![20240519_123633-edit](https://github.com/bassamanator/armbian-orangepi-how-to/assets/61985779/5b7c51d2-547b-44c4-9f80-3bafffab4a11)

**Comment by hqnicolas** [comment]
> The problem was that PRESET_LOCALE=en_CA.UTF-8 was not working, it needs to be PRESET_LOCALE=en_US.UTF-8 
> regardless, I learned this after 6 or so image flashes. Before I discovered that the true issue was locale, I tried to solve the 
> problem by removing on the comments and empty lines. So that warning is a remnant of my problem solving.

Yes, you find a bug!

**Comment by EvilOlaf** [comment]
Thanks for clarifying.
